### ISSUE TITLE
mousetrap fails after `make install`

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#30]
On branch `autotools2`

```
~/work/mousetrap [autotools2|●5] 
23:10 $ sudo make install
/usr/bin/python ./setup.py build \
    --build-base ./build \
    --verbose
running build
Compiling locale files...
Compiling en locale [OK]
running build_py
running egg_info
Removing generated locale files...
writing requirements to mousetrap.egg-info/requires.txt
writing mousetrap.egg-info/PKG-INFO
writing top-level names to mousetrap.egg-info/top_level.txt
writing dependency_links to mousetrap.egg-info/dependency_links.txt
writing entry points to mousetrap.egg-info/entry_points.txt
reading manifest file 'mousetrap.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'mousetrap.egg-info/SOURCES.txt'
make[1]: Entering directory `/home/hjackson/work/mousetrap'
/usr/bin/python ./setup.py install \
    --prefix /usr/local \
    --single-version-externally-managed \
    --record /usr/local/lib/python2.7/site-packages/mousetrap/install_files.txt \
    --verbose
running install
running build
Compiling locale files...
Compiling en locale [OK]
running build_py
running egg_info
writing requirements to mousetrap.egg-info/requires.txt
writing mousetrap.egg-info/PKG-INFO
writing top-level names to mousetrap.egg-info/top_level.txt
writing dependency_links to mousetrap.egg-info/dependency_links.txt
writing entry points to mousetrap.egg-info/entry_points.txt
reading manifest file 'mousetrap.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'mousetrap.egg-info/SOURCES.txt'
running install_lib
creating /usr/local/lib/python2.7/site-packages/mousetrap
copying build/lib/mousetrap/__init__.py -> /usr/local/lib/python2.7/site-packages/mousetrap
creating /usr/local/lib/python2.7/site-packages/mousetrap/plugins
copying build/lib/mousetrap/plugins/__init__.py -> /usr/local/lib/python2.7/site-packages/mousetrap/plugins
copying build/lib/mousetrap/plugins/eyes.py -> /usr/local/lib/python2.7/site-packages/mousetrap/plugins
copying build/lib/mousetrap/plugins/interface.py -> /usr/local/lib/python2.7/site-packages/mousetrap/plugins
copying build/lib/mousetrap/plugins/display.py -> /usr/local/lib/python2.7/site-packages/mousetrap/plugins
copying build/lib/mousetrap/plugins/camera.py -> /usr/local/lib/python2.7/site-packages/mousetrap/plugins
copying build/lib/mousetrap/plugins/nose.py -> /usr/local/lib/python2.7/site-packages/mousetrap/plugins
copying build/lib/mousetrap/i18n.py -> /usr/local/lib/python2.7/site-packages/mousetrap
copying build/lib/mousetrap/image.py -> /usr/local/lib/python2.7/site-packages/mousetrap
copying build/lib/mousetrap/vision.py -> /usr/local/lib/python2.7/site-packages/mousetrap
copying build/lib/mousetrap/main.py -> /usr/local/lib/python2.7/site-packages/mousetrap
creating /usr/local/lib/python2.7/site-packages/mousetrap/tests
copying build/lib/mousetrap/tests/__init__.py -> /usr/local/lib/python2.7/site-packages/mousetrap/tests
copying build/lib/mousetrap/tests/test_mouse_pointer.py -> /usr/local/lib/python2.7/site-packages/mousetrap/tests
copying build/lib/mousetrap/tests/test_vision.py -> /usr/local/lib/python2.7/site-packages/mousetrap/tests
copying build/lib/mousetrap/tests/run_python_tests.py -> /usr/local/lib/python2.7/site-packages/mousetrap/tests
copying build/lib/mousetrap/gui.py -> /usr/local/lib/python2.7/site-packages/mousetrap
creating /usr/local/lib/python2.7/site-packages/mousetrap/locale
creating /usr/local/lib/python2.7/site-packages/mousetrap/locale/en
creating /usr/local/lib/python2.7/site-packages/mousetrap/locale/en/LC_MESSAGES
copying build/lib/mousetrap/locale/en/LC_MESSAGES/mousetrap.mo -> /usr/local/lib/python2.7/site-packages/mousetrap/locale/en/LC_MESSAGES
copying build/lib/mousetrap/config.py -> /usr/local/lib/python2.7/site-packages/mousetrap
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/plugins/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/plugins/eyes.py to eyes.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/plugins/interface.py to interface.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/plugins/display.py to display.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/plugins/camera.py to camera.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/plugins/nose.py to nose.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/i18n.py to i18n.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/image.py to image.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/vision.py to vision.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/main.py to main.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/tests/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/tests/test_mouse_pointer.py to test_mouse_pointer.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/tests/test_vision.py to test_vision.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/tests/run_python_tests.py to run_python_tests.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/gui.py to gui.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/mousetrap/config.py to config.pyc
running install_egg_info
Copying mousetrap.egg-info to /usr/local/lib/python2.7/site-packages/mousetrap-1.0.0a-py2.7.egg-info
running install_scripts
Installing mousetrap script to /usr/local/bin
writing list of installed files to '/usr/local/lib/python2.7/site-packages/mousetrap/install_files.txt'
make[1]: Nothing to be done for `install-data-am'.
make[1]: Leaving directory `/home/hjackson/work/mousetrap'
~/work/mousetrap [autotools2|●5] 
23:10 $ mousetrap
Traceback (most recent call last):
  File "/usr/local/bin/mousetrap", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: mousetrap==1.0.0a
~/work/mousetrap [autotools2|●5]
```

**Comment by kevin-brown** [comment]
The problem here is that autotools is installing MouseTrap to `/usr/local` (which is where Python is installed on Debian/all other systems), but on your system Python is installed to `/usr`.  Because `/usr/local` is not on the path that Python searches, it cannot find the MouseTrap install.

**Comment by StoneyJackson** [comment]
Based on @kevin-brown explanation, the following works

```
./autogen.sh --prefix=/usr
make
sudo make install
```

I updated README.md.

**Comment by ed317023** [comment]
I had the same issue when installing in Fedora on the cslab computers. But the fix worked and MouseTrap was able to run and work and move the mouse with head movements.
