### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by kevin-brown** [GNOME-MouseTrap/mousetrap#41]
Even though OpenCV 2 is not Python 3 compatible and OpenCV 3 has not been released, the code base should still be Python 3 compatible to make it easier to switch over when the time comes.

**Comment by StoneyJackson** [comment]
Close pending review of https://github.com/GNOME-MouseTrap/mousetrap/commit/c0b1985cbb11fe85dbf69aee7d8a9edb956f56cd

**Comment by kevin-brown** [comment]
When using Python 3, I get a segfault when [applying the haar cascades](https://github.com/GNOME-MouseTrap/mousetrap/blob/6d191ef63d273c947e0a0c6b7bb3136ac7b152b4/src/mousetrap/vision.py#L151), but only for the nose (not the face).

The image size is also not being set correctly in Python 3.

---

GDB backtrace:

``` bt
(gdb) bt
#0  0x00002aaac37b65be in int cv::predictOrderedStump<cv::HaarEvaluator>(cv::CascadeClassifierImpl&, cv::Ptr<cv::FeatureEvaluator>&, double&) () from /usr/local/lib/libopencv_objdetect.so.3.0
#1  0x00002aaac37b7117 in cv::CascadeClassifierImpl::runAt(cv::Ptr<cv::FeatureEvaluator>&, cv::Point_<int>, int, double&) () from /usr/local/lib/libopencv_objdetect.so.3.0
#2  0x00002aaac37b9919 in cv::CascadeClassifierInvoker::operator()(cv::Range const&) const () from /usr/local/lib/libopencv_objdetect.so.3.0
#3  0x00002aaac37ba6b1 in cv::CascadeClassifierImpl::detectMultiScaleNoGrouping(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, std::vector<int, std::allocator<int> >&, std::vector<double, std::allocator<double> >&, double, cv::Size_<int>, cv::Size_<int>, bool) () from /usr/local/lib/libopencv_objdetect.so.3.0
#4  0x00002aaac37c28ed in cv::CascadeClassifierImpl::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, std::vector<int, std::allocator<int> >&, std::vector<double, std::allocator<double> >&, double, int, int, cv::Size_<int>, cv::Size_<int>, bool) () from /usr/local/lib/libopencv_objdetect.so.3.0
#5  0x00002aaac37af30b in cv::CascadeClassifierImpl::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>) () from /usr/local/lib/libopencv_objdetect.so.3.0
#6  0x00002aaac37b4135 in cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>) () from /usr/local/lib/libopencv_objdetect.so.3.0
#7  0x00002aaac00b7f29 in pyopencv_CascadeClassifier_detectMultiScale(_object*, _object*, _object*) () from /usr/local/lib/python3.4/dist-packages/cv2.cpython-34m.so
```

---

I compiled OpenCV 3 using [this answer on StackOverflow](http://stackoverflow.com/a/21212023/359284) and had to use the following command for `cmake` to run:

```
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_opencv_java=OFF -D PYTHON_INCLUDE_DIR=/usr/include/python3.4m -D PYTHON_NUMPY_INCLUDE_DIRS=/usr/local/lib/python3.4/dist-packages/numpy/core/include/ -D PYTHON_EXECUTABLE=/usr/bin/python3 -D PYTHON_PACKAGES_PATH=/usr/local/lib/python3.4/dist-packages/ ..
```

**Comment by StoneyJackson** [comment]
OpenCV3 alpha has been released!
http://opencv.org/downloads.html

**Comment by StoneyJackson** [comment]
- [ ] Update dependencies in config files
- [ ] Developers need to install opencv 3 into their python 3
- [ ] Update calls to opencv based on API change
